feat: implement error handling middleware
dana-team/platform-backend pull request #120
Opened 2024-08-19 20:51 UTC by arielsepton

2024-08-19 21:01 UTC, arielsepton commented
I still need to address the `c.Error` lint issue mentioned [here](https://github.com/gin-gonic/gin/issues/2017).

2024-08-27 10:25 UTC, dvirgilad requested changes
Wow! Amazing work.
Left a few (minor) comments,

2024-08-27 10:25 UTC, dvirgilad commented on src/routes/context.go
> +// TODO: implement AddNewErrorToContext
Can this be removed?

2024-08-27 11:05 UTC, arielsepton commented on src/controllers/logs.go
> +	errPodNotFound           = "pod %q not found for Capp %q in namespace %q"
There is a difference between `no pods found` - meaning there are no pods and `Could not get pods` - indicating an error occurred in the fetching process.

2024-08-27 11:08 UTC, arielsepton commented on src/controllers/containers.go
> +	ErrCouldNotGetPod = "failed to get pod %q in the namespace %q"
Despite the other errors that are thrown in pods.go, this error is thrown here.

2024-08-27 11:27 UTC, dvirgilad commented on src/controllers/capp.go
> +	ErrCouldNotGetCapps     = "Could not get capps"
list

2024-08-27 12:02 UTC, dvirgilad approved these changes
/lgtm

2024-08-27 14:55 UTC, mzeevi commented
/approve

2024-08-27 14:56 UTC, merged