Test/secret ctrl
dana-team/platform-backend pull request #80
Opened 2024-07-03 10:43 UTC by dvirgilad

2024-07-04 13:00 UTC, mzeevi requested changes
Needs some changing to align with the latest changes

2024-07-04 13:38 UTC, fran2810 commented on src/controllers/secret_test.go
> +
remove redundant spaces

2024-07-04 13:38 UTC, fran2810 commented on src/controllers/secret_test.go
> +
what is this

2024-07-11 16:13 UTC, mzeevi approved these changes
/lgtm
/approve

2024-07-11 16:14 UTC, merged